# Generated by Django 4.2.1 on 2023-06-26 18:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated time"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="profilepic",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
